// Lista compartida de razas, colores y pesos para los formularios de mascotas.
// Un único origen de datos evita que las listas se desincronicen entre pantallas.

// Razas basadas en la nomenclatura FCI (10 grupos),
// más algunas populares no reconocidas por la FCI.
const FCI_BREEDS = [
  // Grupo 1 — Pastores y boyeros
  "Bearded Collie",
  "Bobtail (Antiguo Pastor Inglés)",
  "Border Collie",
  "Bouvier de Flandes",
  "Boyero de Appenzell",
  "Boyero de Australia (Cattle Dog)",
  "Boyero de Entlebuch",
  "Collie de pelo corto",
  "Collie de pelo largo",
  "Komondor",
  "Kuvasz",
  "Kelpie Australiano",
  "Mudi",
  "Pastor Alemán",
  "Pastor Australiano",
  "Pastor Belga Groenendael",
  "Pastor Belga Laekenois",
  "Pastor Belga Malinois",
  "Pastor Belga Tervueren",
  "Pastor Blanco Suizo",
  "Pastor Catalán (Gos d'Atura)",
  "Pastor de Beauce (Beauceron)",
  "Pastor de Brie (Briard)",
  "Pastor de los Pirineos",
  "Pastor de Shetland",
  "Pastor Holandés",
  "Pastor Islandés",
  "Pastor Maremmano-Abruzés",
  "Pastor Picardo",
  "Pastor Polaco de las Llanuras",
  "Perro Lobo Checoslovaco",
  "Perro Lobo de Saarloos",
  "Puli",
  "Pumi",
  "Schipperke",
  "Welsh Corgi Cardigan",
  "Welsh Corgi Pembroke",

  // Grupo 2 — Pinscher, Schnauzer, Molosoides, boyeros suizos
  "Affenpinscher",
  "Boxer",
  "Boyero de Berna (Bernés)",
  "Bullmastiff",
  "Ca de Bou (Dogo Mallorquín)",
  "Cane Corso",
  "Doberman",
  "Dogo Argentino",
  "Dogo Canario (Presa Canario)",
  "Dogo de Burdeos",
  "Fila Brasileño",
  "Gran Boyero Suizo",
  "Gran Danés (Dogo Alemán)",
  "Hovawart",
  "Landseer",
  "Leonberger",
  "Mastín del Pirineo",
  "Mastín Español",
  "Mastín Inglés (Mastiff)",
  "Mastín Napolitano",
  "Mastín Tibetano",
  "Montaña de los Pirineos",
  "Pastor de Asia Central",
  "Pastor del Cáucaso",
  "Pinscher Alemán",
  "Pinscher Miniatura",
  "Rottweiler",
  "San Bernardo",
  "Schnauzer Estándar",
  "Schnauzer Gigante",
  "Schnauzer Miniatura",
  "Shar Pei",
  "Terranova",
  "Terrier Ruso Negro",
  "Tosa Inu",

  // Grupo 3 — Terriers
  "Airedale Terrier",
  "American Staffordshire Terrier",
  "Australian Silky Terrier",
  "Australian Terrier",
  "Bedlington Terrier",
  "Border Terrier",
  "Bull Terrier",
  "Bull Terrier Miniatura",
  "Cairn Terrier",
  "Cesky Terrier",
  "Dandie Dinmont Terrier",
  "Fox Terrier de pelo duro",
  "Fox Terrier de pelo liso",
  "Glen of Imaal Terrier",
  "Irish Terrier",
  "Jack Russell Terrier",
  "Jagdterrier (Terrier de caza alemán)",
  "Kerry Blue Terrier",
  "Lakeland Terrier",
  "Manchester Terrier",
  "Norfolk Terrier",
  "Norwich Terrier",
  "Parson Russell Terrier",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Skye Terrier",
  "Staffordshire Bull Terrier",
  "Terrier Brasileño",
  "Terrier Irlandés de Trigo Blando",
  "Terrier Japonés",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Yorkshire Terrier",

  // Grupo 4 — Teckels
  "Teckel (Dachshund)",

  // Grupo 5 — Spitz y tipo primitivo
  "Akita Americano",
  "Akita Inu",
  "Basenji",
  "Buhund Noruego",
  "Chow Chow",
  "Cirneco del Etna",
  "Elkhound Noruego",
  "Eurasier",
  "Hokkaido",
  "Husky Siberiano",
  "Keeshond",
  "Kishu",
  "Lundehund Noruego",
  "Malamute de Alaska",
  "Perro Crestado Chino",
  "Perro de Canaán",
  "Perro Finlandés de Laponia",
  "Perro Groenlandés",
  "Perro sin pelo del Perú",
  "Podenco Andaluz",
  "Podenco Canario",
  "Podenco Ibicenco",
  "Podenco Portugués",
  "Pomerania",
  "Samoyedo",
  "Shiba Inu",
  "Shikoku",
  "Spitz Alemán Grande",
  "Spitz Alemán Mediano",
  "Spitz Alemán Pequeño",
  "Spitz Finlandés",
  "Spitz Japonés",
  "Thai Ridgeback",
  "Volpino Italiano",
  "Xoloitzcuintle",

  // Grupo 6 — Sabuesos y rastro
  "Basset Artesiano de Normandía",
  "Basset Azul de Gascuña",
  "Basset Hound",
  "Basset Leonado de Bretaña",
  "Beagle",
  "Beagle Harrier",
  "Bloodhound (San Huberto)",
  "Black and Tan Coonhound",
  "Dálmata",
  "Drever",
  "Foxhound Americano",
  "Foxhound Inglés",
  "Gran Azul de Gascuña",
  "Gran Basset Grifón Vendéen",
  "Grifón Nivernés",
  "Harrier",
  "Otterhound",
  "Pequeño Basset Grifón Vendéen",
  "Porcelaine",
  "Rhodesian Ridgeback",
  "Sabueso de Baviera",
  "Sabueso de Hannover",
  "Sabueso Español",
  "Sabueso Italiano",
  "Sabueso Polaco",
  "Sabueso Suizo",

  // Grupo 7 — Perros de muestra
  "Braco Alemán de pelo corto",
  "Braco Alemán de pelo duro",
  "Braco de Auvernia",
  "Braco de Weimar (Weimaraner)",
  "Braco Francés",
  "Braco Húngaro (Vizsla)",
  "Braco Italiano",
  "Épagneul Bretón",
  "Grifón Korthals",
  "Münsterländer Grande",
  "Münsterländer Pequeño",
  "Perdiguero de Burgos",
  "Perdiguero Portugués",
  "Pointer Inglés",
  "Setter Gordon",
  "Setter Inglés",
  "Setter Irlandés Rojo",
  "Setter Irlandés Rojo y Blanco",
  "Spinone Italiano",
  "Stabyhoun",

  // Grupo 8 — Cobradores, levantadores y de agua
  "Barbet",
  "Chesapeake Bay Retriever",
  "Clumber Spaniel",
  "Cocker Spaniel Americano",
  "Cocker Spaniel Inglés",
  "Curly Coated Retriever",
  "Field Spaniel",
  "Flat Coated Retriever",
  "Golden Retriever",
  "Kooikerhondje",
  "Labrador Retriever",
  "Lagotto Romagnolo",
  "Nova Scotia Duck Tolling Retriever",
  "Perro de Agua Español",
  "Perro de Agua Portugués",
  "Springer Spaniel Inglés",
  "Sussex Spaniel",
  "Wetterhoun (Perro de agua frisón)",

  // Grupo 9 — Compañía
  "Bichón Boloñés",
  "Bichón Frisé",
  "Bichón Habanero",
  "Bichón Maltés",
  "Boston Terrier",
  "Bulldog Francés",
  "Bulldog Inglés",
  "Caniche (Poodle)",
  "Carlino (Pug)",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Chin Japonés",
  "Coton de Tuléar",
  "Grifón de Bruselas",
  "King Charles Spaniel",
  "Kromfohrländer",
  "Lhasa Apso",
  "Papillón",
  "Pekinés",
  "Perro León (Löwchen)",
  "Petit Brabançon",
  "Phalène",
  "Shih Tzu",
  "Spaniel Tibetano",
  "Terrier Ruso (Russkiy Toy)",
  "Terrier Tibetano",

  // Grupo 10 — Lebreles / Galgos
  "Afgano (Lebrel Afgano)",
  "Azawakh",
  "Borzoi (Galgo Ruso)",
  "Deerhound (Lebrel Escocés)",
  "Galgo Español",
  "Galgo Húngaro (Magyar Agár)",
  "Galgo Polaco (Chart Polski)",
  "Greyhound (Galgo Inglés)",
  "Irish Wolfhound (Lebrel Irlandés)",
  "Lebrel Italiano",
  "Saluki",
  "Sloughi",
  "Whippet",

  // Populares no reconocidas por la FCI
  "American Bully",
  "Bulldog Americano",
  "Pitbull",
];

// Traducción al inglés de cada raza (clave = nombre en español tal cual
// aparece arriba, que es lo que ya está guardado en pets.breed).
// Si una raza no aparece aquí (p. ej. una raza escrita a mano en "Otro"),
// se muestra el mismo texto en los dos idiomas — no es un error.
const BREED_EN: Record<string, string> = {
  "Mestizo": "Mixed breed",
  "Otro": "Other",

  "Bearded Collie": "Bearded Collie",
  "Bobtail (Antiguo Pastor Inglés)": "Old English Sheepdog (Bobtail)",
  "Border Collie": "Border Collie",
  "Bouvier de Flandes": "Bouvier des Flandres",
  "Boyero de Appenzell": "Appenzeller Sennenhund",
  "Boyero de Australia (Cattle Dog)": "Australian Cattle Dog",
  "Boyero de Entlebuch": "Entlebucher Mountain Dog",
  "Collie de pelo corto": "Smooth Collie",
  "Collie de pelo largo": "Rough Collie",
  "Komondor": "Komondor",
  "Kuvasz": "Kuvasz",
  "Kelpie Australiano": "Australian Kelpie",
  "Mudi": "Mudi",
  "Pastor Alemán": "German Shepherd",
  "Pastor Australiano": "Australian Shepherd",
  "Pastor Belga Groenendael": "Belgian Shepherd (Groenendael)",
  "Pastor Belga Laekenois": "Belgian Shepherd (Laekenois)",
  "Pastor Belga Malinois": "Belgian Malinois",
  "Pastor Belga Tervueren": "Belgian Shepherd (Tervuren)",
  "Pastor Blanco Suizo": "White Swiss Shepherd",
  "Pastor Catalán (Gos d'Atura)": "Catalan Sheepdog (Gos d'Atura)",
  "Pastor de Beauce (Beauceron)": "Beauceron",
  "Pastor de Brie (Briard)": "Briard",
  "Pastor de los Pirineos": "Pyrenean Shepherd",
  "Pastor de Shetland": "Shetland Sheepdog",
  "Pastor Holandés": "Dutch Shepherd",
  "Pastor Islandés": "Icelandic Sheepdog",
  "Pastor Maremmano-Abruzés": "Maremma Sheepdog",
  "Pastor Picardo": "Picardy Shepherd",
  "Pastor Polaco de las Llanuras": "Polish Lowland Sheepdog",
  "Perro Lobo Checoslovaco": "Czechoslovakian Wolfdog",
  "Perro Lobo de Saarloos": "Saarloos Wolfdog",
  "Puli": "Puli",
  "Pumi": "Pumi",
  "Schipperke": "Schipperke",
  "Welsh Corgi Cardigan": "Cardigan Welsh Corgi",
  "Welsh Corgi Pembroke": "Pembroke Welsh Corgi",

  "Affenpinscher": "Affenpinscher",
  "Boxer": "Boxer",
  "Boyero de Berna (Bernés)": "Bernese Mountain Dog",
  "Bullmastiff": "Bullmastiff",
  "Ca de Bou (Dogo Mallorquín)": "Ca de Bou (Majorca Mastiff)",
  "Cane Corso": "Cane Corso",
  "Doberman": "Doberman",
  "Dogo Argentino": "Dogo Argentino",
  "Dogo Canario (Presa Canario)": "Presa Canario",
  "Dogo de Burdeos": "Dogue de Bordeaux",
  "Fila Brasileño": "Fila Brasileiro",
  "Gran Boyero Suizo": "Greater Swiss Mountain Dog",
  "Gran Danés (Dogo Alemán)": "Great Dane",
  "Hovawart": "Hovawart",
  "Landseer": "Landseer",
  "Leonberger": "Leonberger",
  "Mastín del Pirineo": "Pyrenean Mastiff",
  "Mastín Español": "Spanish Mastiff",
  "Mastín Inglés (Mastiff)": "English Mastiff",
  "Mastín Napolitano": "Neapolitan Mastiff",
  "Mastín Tibetano": "Tibetan Mastiff",
  "Montaña de los Pirineos": "Great Pyrenees",
  "Pastor de Asia Central": "Central Asian Shepherd Dog",
  "Pastor del Cáucaso": "Caucasian Shepherd Dog",
  "Pinscher Alemán": "German Pinscher",
  "Pinscher Miniatura": "Miniature Pinscher",
  "Rottweiler": "Rottweiler",
  "San Bernardo": "St. Bernard",
  "Schnauzer Estándar": "Standard Schnauzer",
  "Schnauzer Gigante": "Giant Schnauzer",
  "Schnauzer Miniatura": "Miniature Schnauzer",
  "Shar Pei": "Shar Pei",
  "Terranova": "Newfoundland",
  "Terrier Ruso Negro": "Black Russian Terrier",
  "Tosa Inu": "Tosa Inu",

  "Airedale Terrier": "Airedale Terrier",
  "American Staffordshire Terrier": "American Staffordshire Terrier",
  "Australian Silky Terrier": "Australian Silky Terrier",
  "Australian Terrier": "Australian Terrier",
  "Bedlington Terrier": "Bedlington Terrier",
  "Border Terrier": "Border Terrier",
  "Bull Terrier": "Bull Terrier",
  "Bull Terrier Miniatura": "Miniature Bull Terrier",
  "Cairn Terrier": "Cairn Terrier",
  "Cesky Terrier": "Cesky Terrier",
  "Dandie Dinmont Terrier": "Dandie Dinmont Terrier",
  "Fox Terrier de pelo duro": "Wire Fox Terrier",
  "Fox Terrier de pelo liso": "Smooth Fox Terrier",
  "Glen of Imaal Terrier": "Glen of Imaal Terrier",
  "Irish Terrier": "Irish Terrier",
  "Jack Russell Terrier": "Jack Russell Terrier",
  "Jagdterrier (Terrier de caza alemán)": "German Hunting Terrier (Jagdterrier)",
  "Kerry Blue Terrier": "Kerry Blue Terrier",
  "Lakeland Terrier": "Lakeland Terrier",
  "Manchester Terrier": "Manchester Terrier",
  "Norfolk Terrier": "Norfolk Terrier",
  "Norwich Terrier": "Norwich Terrier",
  "Parson Russell Terrier": "Parson Russell Terrier",
  "Scottish Terrier": "Scottish Terrier",
  "Sealyham Terrier": "Sealyham Terrier",
  "Skye Terrier": "Skye Terrier",
  "Staffordshire Bull Terrier": "Staffordshire Bull Terrier",
  "Terrier Brasileño": "Brazilian Terrier",
  "Terrier Irlandés de Trigo Blando": "Soft Coated Wheaten Terrier",
  "Terrier Japonés": "Japanese Terrier",
  "Welsh Terrier": "Welsh Terrier",
  "West Highland White Terrier": "West Highland White Terrier",
  "Yorkshire Terrier": "Yorkshire Terrier",

  "Teckel (Dachshund)": "Dachshund",

  "Akita Americano": "American Akita",
  "Akita Inu": "Akita Inu",
  "Basenji": "Basenji",
  "Buhund Noruego": "Norwegian Buhund",
  "Chow Chow": "Chow Chow",
  "Cirneco del Etna": "Cirneco dell'Etna",
  "Elkhound Noruego": "Norwegian Elkhound",
  "Eurasier": "Eurasier",
  "Hokkaido": "Hokkaido",
  "Husky Siberiano": "Siberian Husky",
  "Keeshond": "Keeshond",
  "Kishu": "Kishu",
  "Lundehund Noruego": "Norwegian Lundehund",
  "Malamute de Alaska": "Alaskan Malamute",
  "Perro Crestado Chino": "Chinese Crested Dog",
  "Perro de Canaán": "Canaan Dog",
  "Perro Finlandés de Laponia": "Finnish Lapphund",
  "Perro Groenlandés": "Greenland Dog",
  "Perro sin pelo del Perú": "Peruvian Hairless Dog",
  "Podenco Andaluz": "Andalusian Hound",
  "Podenco Canario": "Canarian Warren Hound",
  "Podenco Ibicenco": "Ibizan Hound",
  "Podenco Portugués": "Portuguese Podengo",
  "Pomerania": "Pomeranian",
  "Samoyedo": "Samoyed",
  "Shiba Inu": "Shiba Inu",
  "Shikoku": "Shikoku",
  "Spitz Alemán Grande": "Giant German Spitz",
  "Spitz Alemán Mediano": "Medium German Spitz",
  "Spitz Alemán Pequeño": "Small German Spitz",
  "Spitz Finlandés": "Finnish Spitz",
  "Spitz Japonés": "Japanese Spitz",
  "Thai Ridgeback": "Thai Ridgeback",
  "Volpino Italiano": "Volpino Italiano",
  "Xoloitzcuintle": "Xoloitzcuintle",

  "Basset Artesiano de Normandía": "Basset Artésien Normand",
  "Basset Azul de Gascuña": "Petit Bleu de Gascogne",
  "Basset Hound": "Basset Hound",
  "Basset Leonado de Bretaña": "Basset Fauve de Bretagne",
  "Beagle": "Beagle",
  "Beagle Harrier": "Beagle Harrier",
  "Bloodhound (San Huberto)": "Bloodhound",
  "Black and Tan Coonhound": "Black and Tan Coonhound",
  "Dálmata": "Dalmatian",
  "Drever": "Drever",
  "Foxhound Americano": "American Foxhound",
  "Foxhound Inglés": "English Foxhound",
  "Gran Azul de Gascuña": "Grand Bleu de Gascogne",
  "Gran Basset Grifón Vendéen": "Grand Basset Griffon Vendéen",
  "Grifón Nivernés": "Griffon Nivernais",
  "Harrier": "Harrier",
  "Otterhound": "Otterhound",
  "Pequeño Basset Grifón Vendéen": "Petit Basset Griffon Vendéen",
  "Porcelaine": "Porcelaine",
  "Rhodesian Ridgeback": "Rhodesian Ridgeback",
  "Sabueso de Baviera": "Bavarian Mountain Hound",
  "Sabueso de Hannover": "Hanoverian Hound",
  "Sabueso Español": "Spanish Hound",
  "Sabueso Italiano": "Italian Hound",
  "Sabueso Polaco": "Polish Hound",
  "Sabueso Suizo": "Swiss Hound",

  "Braco Alemán de pelo corto": "German Shorthaired Pointer",
  "Braco Alemán de pelo duro": "German Wirehaired Pointer",
  "Braco de Auvernia": "Auvergne Pointer",
  "Braco de Weimar (Weimaraner)": "Weimaraner",
  "Braco Francés": "French Pointer",
  "Braco Húngaro (Vizsla)": "Hungarian Vizsla",
  "Braco Italiano": "Italian Pointer",
  "Épagneul Bretón": "Brittany Spaniel",
  "Grifón Korthals": "Wirehaired Pointing Griffon",
  "Münsterländer Grande": "Large Münsterländer",
  "Münsterländer Pequeño": "Small Münsterländer",
  "Perdiguero de Burgos": "Burgos Pointer",
  "Perdiguero Portugués": "Portuguese Pointer",
  "Pointer Inglés": "English Pointer",
  "Setter Gordon": "Gordon Setter",
  "Setter Inglés": "English Setter",
  "Setter Irlandés Rojo": "Irish Red Setter",
  "Setter Irlandés Rojo y Blanco": "Irish Red and White Setter",
  "Spinone Italiano": "Spinone Italiano",
  "Stabyhoun": "Stabyhoun",

  "Barbet": "Barbet",
  "Chesapeake Bay Retriever": "Chesapeake Bay Retriever",
  "Clumber Spaniel": "Clumber Spaniel",
  "Cocker Spaniel Americano": "American Cocker Spaniel",
  "Cocker Spaniel Inglés": "English Cocker Spaniel",
  "Curly Coated Retriever": "Curly Coated Retriever",
  "Field Spaniel": "Field Spaniel",
  "Flat Coated Retriever": "Flat Coated Retriever",
  "Golden Retriever": "Golden Retriever",
  "Kooikerhondje": "Kooikerhondje",
  "Labrador Retriever": "Labrador Retriever",
  "Lagotto Romagnolo": "Lagotto Romagnolo",
  "Nova Scotia Duck Tolling Retriever": "Nova Scotia Duck Tolling Retriever",
  "Perro de Agua Español": "Spanish Water Dog",
  "Perro de Agua Portugués": "Portuguese Water Dog",
  "Springer Spaniel Inglés": "English Springer Spaniel",
  "Sussex Spaniel": "Sussex Spaniel",
  "Wetterhoun (Perro de agua frisón)": "Wetterhoun (Frisian Water Dog)",

  "Bichón Boloñés": "Bolognese",
  "Bichón Frisé": "Bichon Frise",
  "Bichón Habanero": "Havanese",
  "Bichón Maltés": "Maltese",
  "Boston Terrier": "Boston Terrier",
  "Bulldog Francés": "French Bulldog",
  "Bulldog Inglés": "English Bulldog",
  "Caniche (Poodle)": "Poodle",
  "Carlino (Pug)": "Pug",
  "Cavalier King Charles Spaniel": "Cavalier King Charles Spaniel",
  "Chihuahua": "Chihuahua",
  "Chin Japonés": "Japanese Chin",
  "Coton de Tuléar": "Coton de Tulear",
  "Grifón de Bruselas": "Brussels Griffon",
  "King Charles Spaniel": "King Charles Spaniel",
  "Kromfohrländer": "Kromfohrländer",
  "Lhasa Apso": "Lhasa Apso",
  "Papillón": "Papillon",
  "Pekinés": "Pekingese",
  "Perro León (Löwchen)": "Löwchen (Little Lion Dog)",
  "Petit Brabançon": "Petit Brabançon",
  "Phalène": "Phalène",
  "Shih Tzu": "Shih Tzu",
  "Spaniel Tibetano": "Tibetan Spaniel",
  "Terrier Ruso (Russkiy Toy)": "Russian Toy",
  "Terrier Tibetano": "Tibetan Terrier",

  "Afgano (Lebrel Afgano)": "Afghan Hound",
  "Azawakh": "Azawakh",
  "Borzoi (Galgo Ruso)": "Borzoi",
  "Deerhound (Lebrel Escocés)": "Scottish Deerhound",
  "Galgo Español": "Spanish Greyhound",
  "Galgo Húngaro (Magyar Agár)": "Hungarian Greyhound",
  "Galgo Polaco (Chart Polski)": "Polish Greyhound",
  "Greyhound (Galgo Inglés)": "Greyhound",
  "Irish Wolfhound (Lebrel Irlandés)": "Irish Wolfhound",
  "Lebrel Italiano": "Italian Greyhound",
  "Saluki": "Saluki",
  "Sloughi": "Sloughi",
  "Whippet": "Whippet",

  "American Bully": "American Bully",
  "Bulldog Americano": "American Bulldog",
  "Pitbull": "Pit Bull",
};

const COLOR_EN: Record<string, string> = {
  "Atigrado": "Brindle",
  "Beige / Arena": "Beige / Sand",
  "Bicolor": "Bicolor",
  "Blanco": "White",
  "Dorado": "Golden",
  "Gris": "Gray",
  "Manchado": "Spotted",
  "Marrón": "Brown",
  "Negro": "Black",
  "Tricolor": "Tricolor",
  "Otro": "Other",
};

// "Mestizo" primero, resto alfabético (sin duplicados), "Otro" al final.
export const BREEDS: string[] = [
  "Mestizo",
  ...Array.from(new Set(FCI_BREEDS)).sort((a, b) =>
    a.localeCompare(b, "es")
  ),
  "Otro",
];

export const COLORS: string[] = [
  ...[
    "Atigrado",
    "Beige / Arena",
    "Bicolor",
    "Blanco",
    "Dorado",
    "Gris",
    "Manchado",
    "Marrón",
    "Negro",
    "Tricolor",
  ].sort((a, b) => a.localeCompare(b, "es")),
  "Otro",
];

// Pesos exactos: 0.5 a 5 kg de 0.5 en 0.5, y 6 a 90 kg de 1 en 1
export const WEIGHTS: string[] = [
  ...Array.from({ length: 10 }, (_, i) =>
    ((i + 1) * 0.5).toString()
  ),
  ...Array.from({ length: 85 }, (_, i) =>
    (i + 6).toString()
  ),
];

// Devuelve el nombre de la raza en el idioma pedido.
// Si no hay traducción (raza escrita a mano en "Otro"), devuelve el original.
export function getBreedLabel(breed: string, locale: string): string {
  if (locale === "en" && BREED_EN[breed]) {
    return BREED_EN[breed];
  }
  return breed;
}

// Igual que getBreedLabel, pero para colores.
export function getColorLabel(color: string, locale: string): string {
  if (locale === "en" && COLOR_EN[color]) {
    return COLOR_EN[color];
  }
  return color;
}