// Lista compartida de razas, colores y pesos para los formularios de mascotas.
// Un único origen de datos evita que las listas se desincronicen entre pantallas.

// Razas basadas en la nomenclatura FCI (10 grupos),
// más algunas populares no reconocidas por la FCI.
const FCI_BREEDS = [
  // Grupo 1 — Pastores y boyeros
  "Bearded Collie",
  "Bobtail (Antiguo Pastor Inglés)",
  "Border Collie",
  "Bouvier de Flandes",
  "Boyero de Appenzell",
  "Boyero de Australia (Cattle Dog)",
  "Boyero de Entlebuch",
  "Collie de pelo corto",
  "Collie de pelo largo",
  "Komondor",
  "Kuvasz",
  "Kelpie Australiano",
  "Mudi",
  "Pastor Alemán",
  "Pastor Australiano",
  "Pastor Belga Groenendael",
  "Pastor Belga Laekenois",
  "Pastor Belga Malinois",
  "Pastor Belga Tervueren",
  "Pastor Blanco Suizo",
  "Pastor Catalán (Gos d'Atura)",
  "Pastor de Beauce (Beauceron)",
  "Pastor de Brie (Briard)",
  "Pastor de los Pirineos",
  "Pastor de Shetland",
  "Pastor Holandés",
  "Pastor Islandés",
  "Pastor Maremmano-Abruzés",
  "Pastor Picardo",
  "Pastor Polaco de las Llanuras",
  "Perro Lobo Checoslovaco",
  "Perro Lobo de Saarloos",
  "Puli",
  "Pumi",
  "Schipperke",
  "Welsh Corgi Cardigan",
  "Welsh Corgi Pembroke",

  // Grupo 2 — Pinscher, Schnauzer, Molosoides, boyeros suizos
  "Affenpinscher",
  "Boxer",
  "Boyero de Berna (Bernés)",
  "Bullmastiff",
  "Ca de Bou (Dogo Mallorquín)",
  "Cane Corso",
  "Doberman",
  "Dogo Argentino",
  "Dogo Canario (Presa Canario)",
  "Dogo de Burdeos",
  "Fila Brasileño",
  "Gran Boyero Suizo",
  "Gran Danés (Dogo Alemán)",
  "Hovawart",
  "Landseer",
  "Leonberger",
  "Mastín del Pirineo",
  "Mastín Español",
  "Mastín Inglés (Mastiff)",
  "Mastín Napolitano",
  "Mastín Tibetano",
  "Montaña de los Pirineos",
  "Pastor de Asia Central",
  "Pastor del Cáucaso",
  "Pinscher Alemán",
  "Pinscher Miniatura",
  "Rottweiler",
  "San Bernardo",
  "Schnauzer Estándar",
  "Schnauzer Gigante",
  "Schnauzer Miniatura",
  "Shar Pei",
  "Terranova",
  "Terrier Ruso Negro",
  "Tosa Inu",

  // Grupo 3 — Terriers
  "Airedale Terrier",
  "American Staffordshire Terrier",
  "Australian Silky Terrier",
  "Australian Terrier",
  "Bedlington Terrier",
  "Border Terrier",
  "Bull Terrier",
  "Bull Terrier Miniatura",
  "Cairn Terrier",
  "Cesky Terrier",
  "Dandie Dinmont Terrier",
  "Fox Terrier de pelo duro",
  "Fox Terrier de pelo liso",
  "Glen of Imaal Terrier",
  "Irish Terrier",
  "Jack Russell Terrier",
  "Jagdterrier (Terrier de caza alemán)",
  "Kerry Blue Terrier",
  "Lakeland Terrier",
  "Manchester Terrier",
  "Norfolk Terrier",
  "Norwich Terrier",
  "Parson Russell Terrier",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Skye Terrier",
  "Staffordshire Bull Terrier",
  "Terrier Brasileño",
  "Terrier Irlandés de Trigo Blando",
  "Terrier Japonés",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Yorkshire Terrier",

  // Grupo 4 — Teckels
  "Teckel (Dachshund)",

  // Grupo 5 — Spitz y tipo primitivo
  "Akita Americano",
  "Akita Inu",
  "Basenji",
  "Buhund Noruego",
  "Chow Chow",
  "Cirneco del Etna",
  "Elkhound Noruego",
  "Eurasier",
  "Hokkaido",
  "Husky Siberiano",
  "Keeshond",
  "Kishu",
  "Lundehund Noruego",
  "Malamute de Alaska",
  "Perro Crestado Chino",
  "Perro de Canaán",
  "Perro Finlandés de Laponia",
  "Perro Groenlandés",
  "Perro sin pelo del Perú",
  "Podenco Andaluz",
  "Podenco Canario",
  "Podenco Ibicenco",
  "Podenco Portugués",
  "Pomerania",
  "Samoyedo",
  "Shiba Inu",
  "Shikoku",
  "Spitz Alemán Grande",
  "Spitz Alemán Mediano",
  "Spitz Alemán Pequeño",
  "Spitz Finlandés",
  "Spitz Japonés",
  "Thai Ridgeback",
  "Volpino Italiano",
  "Xoloitzcuintle",

  // Grupo 6 — Sabuesos y rastro
  "Basset Artesiano de Normandía",
  "Basset Azul de Gascuña",
  "Basset Hound",
  "Basset Leonado de Bretaña",
  "Beagle",
  "Beagle Harrier",
  "Bloodhound (San Huberto)",
  "Black and Tan Coonhound",
  "Dálmata",
  "Drever",
  "Foxhound Americano",
  "Foxhound Inglés",
  "Gran Azul de Gascuña",
  "Gran Basset Grifón Vendéen",
  "Grifón Nivernés",
  "Harrier",
  "Otterhound",
  "Pequeño Basset Grifón Vendéen",
  "Porcelaine",
  "Rhodesian Ridgeback",
  "Sabueso de Baviera",
  "Sabueso de Hannover",
  "Sabueso Español",
  "Sabueso Italiano",
  "Sabueso Polaco",
  "Sabueso Suizo",

  // Grupo 7 — Perros de muestra
  "Braco Alemán de pelo corto",
  "Braco Alemán de pelo duro",
  "Braco de Auvernia",
  "Braco de Weimar (Weimaraner)",
  "Braco Francés",
  "Braco Húngaro (Vizsla)",
  "Braco Italiano",
  "Épagneul Bretón",
  "Grifón Korthals",
  "Münsterländer Grande",
  "Münsterländer Pequeño",
  "Perdiguero de Burgos",
  "Perdiguero Portugués",
  "Pointer Inglés",
  "Setter Gordon",
  "Setter Inglés",
  "Setter Irlandés Rojo",
  "Setter Irlandés Rojo y Blanco",
  "Spinone Italiano",
  "Stabyhoun",

  // Grupo 8 — Cobradores, levantadores y de agua
  "Barbet",
  "Chesapeake Bay Retriever",
  "Clumber Spaniel",
  "Cocker Spaniel Americano",
  "Cocker Spaniel Inglés",
  "Curly Coated Retriever",
  "Field Spaniel",
  "Flat Coated Retriever",
  "Golden Retriever",
  "Kooikerhondje",
  "Labrador Retriever",
  "Lagotto Romagnolo",
  "Nova Scotia Duck Tolling Retriever",
  "Perro de Agua Español",
  "Perro de Agua Portugués",
  "Springer Spaniel Inglés",
  "Sussex Spaniel",
  "Wetterhoun (Perro de agua frisón)",

  // Grupo 9 — Compañía
  "Bichón Boloñés",
  "Bichón Frisé",
  "Bichón Habanero",
  "Bichón Maltés",
  "Boston Terrier",
  "Bulldog Francés",
  "Bulldog Inglés",
  "Caniche (Poodle)",
  "Carlino (Pug)",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Chin Japonés",
  "Coton de Tuléar",
  "Grifón de Bruselas",
  "King Charles Spaniel",
  "Kromfohrländer",
  "Lhasa Apso",
  "Papillón",
  "Pekinés",
  "Perro León (Löwchen)",
  "Petit Brabançon",
  "Phalène",
  "Shih Tzu",
  "Spaniel Tibetano",
  "Terrier Ruso (Russkiy Toy)",
  "Terrier Tibetano",

  // Grupo 10 — Lebreles / Galgos
  "Afgano (Lebrel Afgano)",
  "Azawakh",
  "Borzoi (Galgo Ruso)",
  "Deerhound (Lebrel Escocés)",
  "Galgo Español",
  "Galgo Húngaro (Magyar Agár)",
  "Galgo Polaco (Chart Polski)",
  "Greyhound (Galgo Inglés)",
  "Irish Wolfhound (Lebrel Irlandés)",
  "Lebrel Italiano",
  "Saluki",
  "Sloughi",
  "Whippet",

  // Populares no reconocidas por la FCI
  "American Bully",
  "Bulldog Americano",
  "Pitbull",
];

// "Mestizo" primero, resto alfabético (sin duplicados), "Otro" al final.
export const BREEDS: string[] = [
  "Mestizo",
  ...Array.from(new Set(FCI_BREEDS)).sort((a, b) =>
    a.localeCompare(b, "es")
  ),
  "Otro",
];

export const COLORS: string[] = [
  ...[
    "Atigrado",
    "Beige / Arena",
    "Bicolor",
    "Blanco",
    "Dorado",
    "Gris",
    "Manchado",
    "Marrón",
    "Negro",
    "Tricolor",
  ].sort((a, b) => a.localeCompare(b, "es")),
  "Otro",
];

// Pesos exactos: 0.5 a 5 kg de 0.5 en 0.5, y 6 a 90 kg de 1 en 1
export const WEIGHTS: string[] = [
  ...Array.from({ length: 10 }, (_, i) =>
    ((i + 1) * 0.5).toString()
  ),
  ...Array.from({ length: 85 }, (_, i) =>
    (i + 6).toString()
  ),
];